name: CI

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: application.yaml 파일 생성
        run:
          echo "${{ secrets.APPLICATION }}" > ./application.yaml
        shell:
          bash

      - name: Build with Gradle
        run: | 
          chmod +x gradlew
          ./gradlew build -x test