name: CD

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-20.04
    env:
      working-directory: Second Seminar/SecondSeminar

    steps: 
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yaml 생성 및 빌드
      run: | 
          echo "${{ secrets.APPLICATION }}" > ./application.yaml

          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}

    - name: Build And Push Docker Image
      run: |
        docker build --platform linux/amd64 -t sunseo18/do-sopt-seminar .
        docker push sunseo18/do-sopt-seminar
        
  deploy-cd:      
    needs: deploy-ci
    runs-on: ubuntu-20.04

    steps:
    - name: run docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RELEASE_SERVER_IP }}
        username: ${{ secrets.RELEASE_SERVER_USER }}
        key: ${{ secrets.RELEASE_SERVER_KEY }}
        script: |
          docker run -d --name do-sopt-seminar-8080 -p 8080:8080 sunseo18/do-sopt-seminar


  
    
